---
- block:
    # TODO: is this really doing a "apt full-upgrade"?
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      become: true

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ current_user }}/.ssh
        state: directory
        mode: '0700'
        owner: {{ current_user }}
        group: {{ current_user }}

    - name: Install dstat
      apt:
        name: dstat
        state: present
      become: true

    #############################################
    # snap
    #
    - name: Install snapd
      apt:
        name: snapd
        state: present
      become: true

    - name: Install package with snap
      shell: snap install core
      become: true

    #############################################
    # zsh
    #
    - name: Install zsh
      apt:
        name: zsh
        state: present
      become: true

    - name: Change default shell to zsh
      user:
        name: "{{ current_user }}"
        shell: /usr/bin/zsh
      become: true

    - name: Check if oh-my-zsh already installed
      stat:
        path: /home/{{ current_user }}/.oh-my-zsh
      register: oh_my_zsh

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ current_user }}/.oh-my-zsh
      when: not oh_my_zsh.stat.exists

    - name: extend alias 
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: 'alias ll="ls -l"'
        state: present

    #############################################
    # ... finishing
    #
    - name: add snap binaries to PATH
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: 'export PATH=$PATH:/snap/bin'
        state: present
