---
- block:
    # TODO: is this really doing a "apt full-upgrade"?
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      become: true

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ current_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    #############################################
    # monitoring tooling
    #
    - name: Install perfomance monitoring tools
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - 'dstat'
        - 'procps'  # for vmstat

    #############################################
    # snap
    #
    - name: Install snapd
      apt:
        name: snapd
        state: present
      become: true

    - name: Install package with snap
      shell: snap install core
      become: true

    - name: extend .zshrc
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: '{{ item }}'
        state: present
      with_items: 
        - 'export PATH=$PATH:/snap/bin'
