---
- block:
    # TODO: is this really doing a "apt full-upgrade"?
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      become: true

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ current_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ current_user }}"
        group: "{{ current_user }}"

    #############################################
    # monitoring tooling
    #
    - name: Install perfomance monitoring tools
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - 'dstat'
        - 'procps'  # for vmstat

    #############################################
    # snap
    #
    - name: Install snapd
      apt:
        name: snapd
        state: present
      become: true

    - name: Install package with snap
      shell: snap install core
      become: true

    #############################################
    # zsh
    #
    - name: Install zsh
      apt:
        name: zsh
        state: present
      become: true

    - name: Change default shell to zsh
      user:
        name: "{{ current_user }}"
        shell: /usr/bin/zsh
      become: true

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ current_user }}/.oh-my-zsh

    - name: extend .zshrc
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: ''
        state: present
      with_items: 
        - 'alias cdhomelabansible="cd ~/src/homelab-ansible"'
        - 'alias la="ls -la"'
        - 'alias ll="ls -l"'
        - 'alias lt="ls -ltr"'
        - 'export EDITOR=vi'

    #############################################
    # ... finishing
    #
    - name: add snap binaries to PATH
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: 'export PATH=$PATH:/snap/bin'
        state: present
