---
- block:
    - name: Install k9s
      shell: |
        wget -O /tmp/k9s.tar.gz https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_{{ architecture }}.tar.gz
        tar -xzf /tmp/k9s.tar.gz
        mv k9s /usr/local/bin/
      args:
        creates: /usr/local/bin/k9s

  become: true
