---
- name: Setup Homelab Raspberry Pi Node
  hosts: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install snapd
      apt:
        name: snapd
        state: present

    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/zsh

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ lookup('env', 'USER') }}/.oh-my-zsh

    - name: Install microk8s
      snap:
        name: microk8s
        state: present
        classic: yes

    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Enable microk8s addons
      shell: |
        microk8s enable dns storage
      become: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install k9s
      shell: |
        wget https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_arm64.tar.gz
        tar -xzf k9s_Linux_arm64.tar.gz
        mv k9s /usr/local/bin/
      args:
        creates: /usr/local/bin/k9s
