---
- block:

    - name: Install latest helm version
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sh -
      args:
        creates: /usr/local/bin/helm

  become: true
