---
- block:
    - name: Install microk8s
      snap:
        name: microk8s
        state: present
        classic: yes
      become: true

    - name: Add user to microk8s group
      user:
        name: "{{ current_user }}"
        groups: microk8s
        append: yes
      become: true

    - name: Enable microk8s addons
      shell: |
        /snap/bin/microk8s enable dns storage
      become: true

    - name: extend alias 
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: 'alias k="microk8s kubectl"'
        state: present
