---
- block:
    - name: Install microk8s
      snap:
        name: microk8s
        state: present
        classic: yes
      become: true

    - name: Add user to microk8s group
      user:
        name: "{{ current_user }}"
        groups: microk8s
        append: yes
      become: true

    - name: Enable microk8s addons
      shell: |
        /snap/bin/microk8s enable dns storage
      become: true

    - name: configure .alias
      copy:
        src: files/alias.zsh
        dest: /home/{{ current_user }}/{{ oh_my_zsh_custom_folder }}/aliases-microk8s.zsh
      become: false
