---
- block:
    - name: Install microk8s
      snap:
        name: microk8s
        state: present
        # Using the --classic flag ensures that MicroK8s has the necessary permissions
        # to function properly, especially when interacting with other system components
        # and resources.
        classic: yes
      become: true

    - name: Add user to microk8s group
      user:
        name: "{{ current_user }}"
        groups: microk8s
        append: yes
      become: true

    - name: ensure microk8s is running
      shell: |
        /snap/bin/microk8s start
        /snap/bin/microk8s status --wait-ready
      become: true

    - name: create ~/.kube/config for microk8s
      shell: |
        mkdir -p /home/{{ current_user }}/.kube
        /snap/bin/microk8s kubectl config view --raw > ~/.kube/config

    - name: Enable microk8s addons
      shell: |
        /snap/bin/microk8s enable {{ item }}
      become: true
      with_items:
        - 'dns'
        - 'storage'

    - name: extend alias
      lineinfile:
        path: /home/{{ current_user }}/.zshrc
        create: yes
        line: "{{ item }}"
        state: present
      with_items:
        - 'alias k="microk8s kubectl"'
        - 'alias kubectl="microk8s kubectl"'
