---
- block:
    - name: Install zsh
      apt:
        name: zsh
        state: present
      become: true

    - name: Change default shell to zsh
      user:
        name: "{{ current_user }}"
        shell: /usr/bin/zsh
      become: true

    - name: Install oh-my-zsh
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
      args:
        creates: /home/{{ current_user }}/.oh-my-zsh

    - name: configure .alias
      copy:
        src: files/alias.zsh
        dest: /home/{{ current_user }}/{{ oh_my_zsh_custom_folder }}/aliases-shell.zsh

  become: true
