---
- block:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install snapd
      apt:
        name: snapd
        state: present

  become: true
