---

- name: Setup Homelab Raspberry Pi OS Node
  hosts: local
  vars_files:
    vars.yaml
  vars:
    current_user: "{{ lookup('env', 'USER') }}"
  roles:
    - basics
    - zsh
    - git
    #- microk8s
    - k3s
    - kubens
    - docker
    - k9s
    - helm