---
- block:

    - name: derive artifact_identifier (aarch64)
      set_fact:
        artifact_identifier: "linux_arm64"
      when: ansible_architecture == "aarch64"

    - name: Fetch the latest release information from GitHub API
      shell: |
        latest_release=$(curl -s https://api.github.com/repos/ahmetb/kubectx/releases/latest)

        # Extract the tag name (version) and download URL for the appropriate binary
        latest_version=$(echo "$latest_release" | grep -oP '"tag_name": "\K(.*)(?=")')
        download_url=$(echo "$latest_release" | grep -oP '"browser_download_url": "\K(.*)(?=")' | grep {{ artifact_identifier }}.tar.gz)

        echo "$latest_version"
      register: latest_version

    - name: Install latest kubens version ({{ latest_version.stdout }})
      shell: |
        cd /tmp
        curl -o kubens.tar.gz -s -L https://github.com/ahmetb/kubectx/releases/download/{{ latest_version.stdout }}/kubens_{{ latest_version.stdout }}_{{ artifact_identifier }}.tar.gz
        tar xvfz kubens.tar.gz
        mv kubens /usr/local/bin/kubens
      args:
        creates: /usr/local/bin/kubens
      become: true
