#!/usr/bin/env bash
#
# Run all dotfiles installers.
DOTFILES_SCRIPTS=$(dirname "$0")

source ${DOTFILES_SCRIPTS}/functions

set -e

# find the installers and run them iteratively
find ${DOTFILES_ROOT} -name install.sh | while read installer ; do bash -c "${installer}" ; done